from typing import Protocol


class GraphPersistenceManagerPort(Protocol):
    def load_project_graph(self, project_root: str, strict: bool = True): ...

    def save_project_graph(self, graph, project_root: str): ...

    def load_ir_graph_for_file(self, file_path: str, strict: bool = True): ...

    def save_ir_graph(self, ir_graph, file_path: str) -> None: ...
